### ISSUE TITLE
感谢你的开源工作，请问这篇论文有预印本吗，有没有挂在ARXIV呢？

### ISSUE THREAD

**Issue by morte2025** [sunjingnjupt/PE-HL-PF#1]

**Comment by sunjingnjupt** [comment]
Thank you for your recognition and interest in our work. Considering that this work has not been accepted by the journal yet, the work has not been published in arxiv. We strive to have the paper accepted early and published as soon as possible.

**Comment by sunjingnjupt** [comment]
感谢您对该工作的关注， 很抱歉现在才回复这个问题， 由于论文最近才被接受。
期刊名字： Dynamic Vehicle Pose Estimation with Heuristic L-Shape Fitting and Grid-Based Particle Filter
